### PR TITLE
feat: build documentation with docs from DSP-APP and DSP-API repo (DSP-1066)

### PR DESCRIPTION
**Pull request by kilchenmann**
resolves DSP-1066

### CODE REVIEW

**Comment by kilchenmann** [comment]
For the reviewers: If you want to run the documentation locally, please follow the instructions in the updated README <https://github.com/dasch-swiss/dsp-docs/tree/wip/dsp-1066-test-monorepo#developers>

**Review by waychal — CHANGES_REQUESTED** [review]
* Is it possible to increase the font in table? It looks very small to me.

image


* Some of the diagrams look very big on page

image

* Image is missing on `http://127.0.0.1:8000/developers/dsp-api/rdf/` page.

Screenshot 2021-06-10 at 11 08 03

**Comment by kilchenmann** [comment]
> * Is it possible to increase the font in table? It looks very small to me.
> 
> * Some of the diagrams look very big on page
> 

We should create a task for these two issues, which are not directly part of this PR


> * Image is missing on `http://127.0.0.1:8000/developers/dsp-api/rdf/` page.
> 

I will fix the issue with the image. But the URL path you mentioned (`/developers/dsp-api/rdf/`) doesn't exist anymore in this PR 😳

**Comment by kilchenmann** [comment]
I fixed the issue with the missing image. But you can't test it locally because of a CORS issue (http on localhost and the image from https source)

**Review by mdelez — APPROVED** [review]
Functionality works well! Let me know when you need me to proofread the content.

**Pull request merged**
