### PR TITLE
Wip/getting started - link adapted

### PR DESCRIPTION
**Pull request by gautschr**

### CODE REVIEW

**Comment by kilchenmann** [comment]
@gautschr: What is the status of this PR? I saw some conflicts we have because of another, just merged PR.

**Comment by gautschr** [comment]
Ivan merged the branch for me in February. Only the last issue (correction of one link) is still not resolved I just realised.

**Comment by kilchenmann** [comment]
Thanks @gautschr for the quick response. But I do not understand, when it's merged, why is the PR still open 😳 If it's okay, I will resolve the merge conflicts above and then we have to see, if we have to merge this PR or not 😉

**Comment by kilchenmann** [comment]
@gautschr I will merge this PR. It contains some changes, that are needed. e.g. a dead link to gravsearch queries.

**Pull request merged**
