### PR TITLE
Update documentation using the name DSP-UI

### PR DESCRIPTION
**Pull request by flavens**
For more info: [DSP 248](https://dasch.myjetbrains.com/youtrack/issue/DSP-248)

### CODE REVIEW

**Comment by kilchenmann** [comment]
@flavens I found some dead links. Should I resolve them?

**Comment by flavens** [comment]
> @flavens I found some dead links. Should I resolve them? e.g. in main index and readme file

Really? I though I checked everything (but only in the dsp-ui dev + contribution docs)! I think it is quicker if you fix them. Thanks!

**Comment by kilchenmann** [comment]
> > @flavens I found some dead links. Should I resolve them? e.g. in main index and readme file
> 
> Really? I though I've checked everything (but only in the dsp-ui dev + contribution docs)! I think it is quicker if you fix them. Thanks!

Look for "knora-ui" in all folders. Probably we should also rename the images folder in assets from knora-ui to dsp-ui to be consistent.

**Comment by kilchenmann** [comment]
@flavens I will fix it asap

**Comment by kilchenmann** [comment]
@flavens I updated the files. Can you have a look on it when you have time...

**Comment by flavens** [comment]
> @flavens I updated the files. Can you have a look on it when you have time...

It is ok for me. I can review the PR.

**Pull request merged**
